### PR TITLE
Use govuk-eleventy-plugin

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
**Updated 21 March 2022**

Parts of this project have now been abstracted into [a plugin for Eleventy](https://x-govuk.github.io/govuk-eleventy-plugin/), a set of [prototype components](https://x-govuk.github.io/govuk-prototype-components/) and [a markdown renderer that decorates HTML with the typography classes](https://github.com/x-govuk/markdown-it-govuk) from `govuk-frontend`.

This means the design history template can be *massively* simplified, providing only the specific features required for a design history:

* Post and page layouts that accept an array of screenshots (with associated print styles)
* A component to show previews of email content
* Scripts to generate pages of screenshots
* `Profile` for hosting a design history on Heroku
* `netlify.toml` for hosting a design history on Netlify

### Configuration
  * Eleventy (at least 99% of it)
  * Nunjucks
  * `markdown-it` and its many plugins

### Layouts:
  * Collection
  * Search index
  * Sitemap

### Components:
  * `appArticle`
  * `appDocumentList`
  * `appGallery`
  * `appHeader`
  * `appMasthead`
  * `appPagination`
  * `appProse`
  * `appRelated`
  * `appSiteSearch`

### Common filters
  * `date`
  * `items`
  * `markdown`
  * `noOrphans`
  * `pretty`
  * `tokenize`

***

With that in mind, this PR might be considered a v2.0.0 of the `govuk-design-history` project, as upgrading to use this plugin will require a few changes (although mainly deleting things).

Here is an update to a smaller design history, which also demonstrates the the new ability to customise a site’s branding, header and footer:

* https://github.com/roobottom/core-design-history/pull/7
* https://core-design-history.netlify.app

### CODE REVIEW

**Comment by frankieroberto** [comment]
I like the idea of abstracting some of these out, but I wonder whether it'd be better and more widely useful to break it down into a collection of smaller plugins rather than one big-ish one which contains a bunch of mostly unrelated filters, components and configuration?

I think also where we abstract components out, we should change the prefix so that the macros and CSS no longer start with `app`, as I would expect those to be app-specific and within the repo? We probably shouldn't use `govuk` either as that’s kinda reserved for `govuk-frontend`, so would have to use something else?  Possibly `x-govuk` / `xGovuk` (where the `x` stands for "cross government" / unofficial)? Could be hosted under the [`x-govuk`](https://github.com/x-govuk/) GitHub org too?

**Comment by paulrobertlloyd** [comment]
> I wonder whether it'd be better and more widely useful to break it down into a collection of smaller plugins rather than one big-ish one which contains a bunch of mostly unrelated filters, components and configuration?

I’ve actually started work on a separate components package (see: https://github.com/paulrobertlloyd/govuk-prototype-rig/tree/main/packages/govuk-prototype-components/proto/components). My thought was to then pull that into the Eleventy plugin. But there would still need to be a few document related components provided by the plugin, at least to start off with.

> I think also where we abstract components out, we should change the prefix so that the macros and CSS no longer start with app.

I agree. In the prototype rig I’ve been using `rig-`, but then when I abstracted the components used `proto-`, but I quite like `x-govuk-`; very similar to non-standard email and HTTP headers.

> Could be hosted under the x-govuk GitHub org too?

I’ve just been booted from the DFE-Digital org, making maintaining this project much harder. I think it’d need to be moved to an organisation where contributors control access, not digital account managers in some distant team. What do you think to moving this repo over to <https://github.com/x-govuk> @fofr?

**Comment by frankieroberto** [comment]
> > I wonder whether it'd be better and more widely useful to break it down into a collection of smaller plugins rather than one big-ish one which contains a bunch of mostly unrelated filters, components and configuration?
> 
> I’ve actually started work on a separate components package (see: https://github.com/paulrobertlloyd/govuk-prototype-rig/tree/main/packages/govuk-prototype-components/proto/components). My thought was to then pull that into the Eleventy plugin. But there would still need to be a few document related components provided by the plugin, at least to start off with.

Would a repo per component be overkill? 🤔  pros: easier to pick and choose which ones you want, and drop any that get upstreamed into govuk-frontent, cons: probably harder to maintain?

> > I think also where we abstract components out, we should change the prefix so that the macros and CSS no longer start with app.
> 
> I agree. In the prototype rig I’ve been using `rig-`, but then when I abstracted the components used `proto-`, but I quite like `x-govuk-`; very similar to non-standard email and HTTP headers.

Another option would be no prefix at all, but that might be confusing for anyone trying to track down where some css came from. The `x-govuk` prefix reminds me a bit of non-standard CSS features too...

> > Could be hosted under the x-govuk GitHub org too?
> 
> I’ve just been booted from the DFE-Digital org, making maintaining this project much harder. I think it’d need to be moved to an organisation where contributors control access, not digital account managers in some distant team. What do you think to moving this repo over to https://github.com/x-govuk @fofr?

Sounds like a perfect use case for the `x-govuk` GitHub org. I can make you an admin.

**Comment by paulrobertlloyd** [comment]
> Would a repo per component be overkill? 🤔 pros: easier to pick and choose which ones you want, and drop any that get upstreamed into govuk-frontent, cons: probably harder to maintain?

Hmmm, possibly? Using a monorepo would make it easier to maintain, I’ve had success with that on https://github.com/getindiekit/indiekit. Could have a package that is a wrapper that includes all the components, too.

I think versioned releases, with breaking changes is probably a good way to handle components getting upstreamed.

**Comment by paulrobertlloyd** [comment]
🛎️ @frankieroberto @fofr I’ve updated this PR to use v2.0.0-beta of the GOV.UK Eleventy Plugin. I think this addresses some of the earlier concerns raised at the end of last year.

**Review by frankieroberto — APPROVED** [review]
👍🏻

**Comment by paulrobertlloyd** [comment]
@fofr gave me the all clear too… I think getting him to approve things while he’s on holiday is my new strategy in life 🤣

**Pull request merged**
